Batteries:
  Li-ion:
    charge_temperature:
      min: 0
      max: 45
    state_of_charge:
      min: 20
      max: 80
    # TODO: [Optional] Add sensor for check the charge_rate of the battery
    charge_rate:
      min: 0
      max: 0.8
